### ISSUE TITLE
How to config to use ResNet34?

### ISSUE THREAD

**Issue by twshen2000** [dipu-bd/face-anti-spoofing#2]
I can't use the pre-trained model MyresNet34.pth.

**Comment by dipu-bd** [comment]
In some latest changes the `master` is locked to `MyVggNet16`

If you want to use custom pre-trained model I suggest following this commit:

https://github.com/dipu-bd/face-anti-spoofing/tree/601328d33af19857c87b82a647fcd6d923fc6718
